### ISSUE TITLE
Giveaways not ending.

### ISSUE THREAD

**Issue by teddyrasmussen** [AXVin/AXVin-Cogs#4]
I had an issue where giveaways were not ending on time, or at all.
How to reproduce:
1. Set the delay to 100.
2. Make a giveaway. For the time, put something like "in 1 day" or "in 8 hours".

**Comment by AXVin** [comment]
What could have gone wrong:

• The bot was restarted before the end Message was sent
• The bot was not given enough time (100+ seconds) to consider giveaway end
• No one joined the giveaway. (I know it was fixed in #1 but it still might be the case)

I would recommend using a fast interval time in these cases @CraziiAce

**Comment by teddyrasmussen** [comment]
Thanks for that.
I decided not to use a fast interval as I could get ratemited. For the two times I tried, the giveaways were 2 days and 8 hours, so that's why I chose a slow interval.

**Comment by AXVin** [comment]
@CraziiAce Fast Giveaway Intervals don't really cause ratelimits. The bot only edits the channels if the channel name is different. This only happens after a minute (unless the counter is less than 1 minute)
Longer Intervals are only beneficial for lowering your CPU usage in case you have like 100+ giveaways/countdowns running.

I will be closing this issue now 😀

**Comment by teddyrasmussen** [comment]
I'm sorry I have to keep bothering you, but it's still not working. I set the interval to 5, the fastest it can be, and I ran giveaways for 1 minute, 1 hour, and 5 hours. None of them ended at the time in the footer in the giveaway message, or at all for that matter.

**Comment by teddyrasmussen** [comment]
@AXVin I got a [screenshot ](https://gyazo.com/8866dac4c53f6da12a8507c34a2b037f) of it too. I took that at 1:41 PM.
